#IF YOU DON'T KNOW WHAT YOU'RE DOING, DON'T EDIT THIS FILE BY HAND
version: 0.0.0
use-alternative-chunkloader: true
ignore-interval: 10
refresh-in-ticks: 50
next-id: 0
next-route: 0
owners: true
permissions: true
op: false
chunks: '{\"chdvector\":[]}'